### ISSUE TITLE
Test if we can use require("basil.js")

### ISSUE THREAD

**Issue by fabiantheblind** [vogelino/es2015-2-extendScript-build#12]
What if we set in package.json

    "main":"basil.bundle.js"  

can we call it just like any other module?

**Comment by fabiantheblind** [comment]
Okay. 

    require('basil.js');

Works. The only thing is we get an error with

    #target "InDesign"

in line 41  

    /Users/icke/Desktop/basiltest/node_modules/basil.js/basil.bundle.js:41
    #target "InDesign";
    ^
   
    SyntaxError: Unexpected token ILLEGAL
        at exports.runInThisContext (vm.js:53:16)
        at Module._compile (module.js:387:25)
        at Object.Module._extensions..js (module.js:422:10)
        at Module.load (module.js:357:32)
        at Function.Module._load (module.js:314:12)
        at Module.require (module.js:367:17)
        at require (internal/module.js:16:19)
        at Object.<anonymous> (/Users/icke/Desktop/basiltest/index.js:1:63)
        at Module._compile (module.js:413:34)
        at Object.Module._extensions..js (module.js:422:10)

Let's see how this turns out.
